[package]
name = "senders_receivers"
version = "0.1.0"
edition = "2021"
authors = ["Ariane"]
license = "BSD-2-Clause"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
threadpool = "1.8"
rand = "0.8"
